name: CLI only binary build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build cli only binary
      run: docker run -v $PWD:/volume --rm -t clux/muslrust:stable cargo build --release --no-default-features --features self-packed
